name: Deploy

on: [push]

jobs:
  build:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
         env:
        FTP_SERVER: http://ns3138884.ip-5-39-76.eu/
        FTP_USERNAME: root
        FTP_PASSWORD: allahou786  
        ARGS: --delete
