name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: http://ns3138884.ip-5-39-76.eu/
        username: root
        password: allahou786
        port: 22
        source: "tests/a.txt,tests/b.txt"
        target: "test"
        
        
