name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v1
      with:
        host: http://ns3138884.ip-5-39-76.eu/
        user: root
        password: allahou786
        localDir: "dist"
        remoteDir: "www"
