name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: http://ns3138884.ip-5-39-76.eu/
        USERNAME : root
        PASSWORD : allahou786
        PORT : 22
        with:
        source: "."
        target: "/opt/app"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        HOST: http://ns3138884.ip-5-39-76.eu/
        USERNAME : root
        PASSWORD : allahou786
        PORT : 22
        script: cat /opt/app/README.md
